//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyBanVe.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class SalesTicket
    {
        public int Id { get; set; }
        public string BillNo { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<int> SeqNo { get; set; }
        public Nullable<int> IdTicket { get; set; }
        public string NameTicket { get; set; }
        public Nullable<decimal> PriceTicket { get; set; }
        public Nullable<int> Quantity { get; set; }
        public Nullable<decimal> TotalAmount { get; set; }
        public string UserId { get; set; }
        public Nullable<int> Sta { get; set; }
    }
}
