//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyBanVe.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserGroup
    {
        public string IdGroup { get; set; }
        public string NameGroup { get; set; }
    }
}
